# Generated by Django 3.1.7 on 2021-03-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='withdrawal',
            field=models.DateTimeField(blank=True, null=True, verbose_name='withdrawal'),
        ),
    ]
