# Generated by Django 3.1.7 on 2021-03-13 22:39

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='withdrawal_username',
            field=models.CharField(default=None, max_length=150, null=True, verbose_name='withdrawal_username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
